=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/alwaysadditems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="AlwaysAddItems">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AlwaysAddItem" type="ItemType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element ref="ItemID"/>
			<xs:element ref="name" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="ItemID" type="xs:unsignedInt"/>
</xs:schema>

=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/alwaysadditems.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<AlwaysAddItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\WebDesign\RaidAttendancePoints\rap\plugins\ctrt\xml\alwaysadditems.xsd">
	<AlwaysAddItem>
		<ItemID>17966</ItemID>
		<name>Onyxia Hide Backpack</name>
	</AlwaysAddItem>
	<AlwaysAddItem>
		<ItemID>20873</ItemID>
		<name>Alabaster Idol</name>
	</AlwaysAddItem>
	<AlwaysAddItem>
		<ItemID>17966</ItemID>
		<name>Onyxia Scale Cloak</name>
	</AlwaysAddItem>
	<AlwaysAddItem>
		<ItemID>20866</ItemID>
	</AlwaysAddItem>
</AlwaysAddItems>
