=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/playeraliases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PlayerAliases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PlayerAlias" type="PlayerAliasType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PlayerAliasType">
		<xs:sequence>
			<xs:element ref="alias"/>
			<xs:element ref="member"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="member" type="xs:string"/>
	<xs:element name="alias" type="xs:string"/>
</xs:schema>

=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/playeraliases.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<PlayerAliases xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\WebDesign\RaidAttendancePoints\rap\plugins\ctrt\xml\playeraliases.xsd">
	<PlayerAlias>
		<alias>bank</alias>
		<member>disenchanted</member>
	</PlayerAlias>
	<PlayerAlias>
		<alias>Twink1ofMainChar1</alias>
		<member>MainChar1</member>
	</PlayerAlias>
	<PlayerAlias>
		<alias>Twink2ofMainChar1</alias>
		<member>MainChar1</member>
	</PlayerAlias>
</PlayerAliases>
