=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/raidnotetriggers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="RaidNoteTriggers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RaidNoteTrigger" type="RaidNoteTriggerType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RaidNoteTriggerType">
		<xs:sequence>
			<xs:element ref="trigger"/>
			<xs:element ref="result"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="trigger" type="xs:string"/>
	<xs:element name="result" type="xs:string"/>
</xs:schema>

=== Illydth/wrsdkp/plugins/ctrt/docs/xml_layouts/raidnotetriggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by garrett (sony) -->
<RaidNoteTriggers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\WebDesign\RaidAttendancePoints\rap\plugins\ctrt\xml\raidnotetriggers.xsd">
	<RaidNoteTrigger>
		<trigger>Bloodlord</trigger>
		<result>Bloodlord Mandokir</result>
	</RaidNoteTrigger>
	<RaidNoteTrigger>
		<trigger>Azuregos</trigger>
		<result>Azuregos</result>
	</RaidNoteTrigger>
	<RaidNoteTrigger>
		<trigger>Kazzak</trigger>
		<result>Kazzak</result>
	</RaidNoteTrigger>
</RaidNoteTriggers>
